version: '3'
services:
  apt-server-arm64: &apt-server
    container_name: apt-server-arm64
    build:
      dockerfile: Dockerfile
      args:
        DOCKER_ARCH: arm64v8
        PACKAGE_ARCHS: armhf,arm64,amd64
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    volumes:
      - /opt/debs:/opt/debs
  apt-server-amd64:
    <<: *apt-server
    container_name: apt-server-amd64
    build:
      dockerfile: Dockerfile
      args:
        DOCKER_ARCH: amd64
